[project]
name = "creamoda_be"
version = "0.1.0"
description = "ðŸ§‘â€ðŸ’» Python FastAPI backend for CERAMODA ðŸ‘—"
authors = [
    { name = "Mark Sun", email = "sunyunfei201@gmail.com" },
]
dependencies = [
    "fastapi==0.110.0",
    "uvicorn==0.27.1",
    "python-dotenv==1.0.1",
    "httpx==0.27.0",
    "python-jose[cryptography]==3.3.0",
    "pydantic[email]==2.6.1",
    "pydantic-settings==2.1.0",
    "idna==3.6",
    "certifi==2024.2.2",
    "requests>=2.32.3",
]
requires-python = "==3.11.*"
readme = "README.md"
license = { text = "MIT" }


[tool.pdm]
distribution = false
